name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create environment file
        run: |
          cat <<EOF > .env
          DATABASE_URL=postgresql+psycopg://postgres:Artillary177%23@postgres:5432/Rag_DB
          REDIS_URL=redis://redis:6379/0
          API_KEY=test-api-key
          OPENAI_API_KEY=test-key
          
          RAW_DIR = /app/data/raw
          PROCESSED_DIR = /app/data/processed
          VECTOR_STORE_DIR = /app/embeddings/cache
          
          REDIS_HOST=redis
          REDIS_PORT=6379
          REDIS_DB=0
          REDIS_TTL=3600
          
          EOF

      - name: Build containers
        run: docker compose build

      - name: Run Ruff
        run: >
          docker compose run --rm --no-deps
          rag_api
          ruff check .

      - name: Run MyPy
        run: >
          docker compose run --rm --no-deps
          rag_api
          mypy --config-file mypy.ini
          api Database ingest retrieval reranking LLM Response utils

      # Start only the services required by tests.
      # Do not start rag_api or celery here.
      - name: Start test dependencies
        run: docker compose up -d postgres redis

      - name: Show container status
        run: docker compose ps

      - name: Check memory before tests
        run: docker stats --no-stream

      # Creates a temporary container and overrides the Uvicorn command with pytest.
      - name: Run Pytest
        run: >
          docker compose run --rm --no-deps
          rag_api
          pytest -vv -x --tb=long py_tests
          --cov=api
          --cov=Database
          --cov=ingest
          --cov=retrieval
          --cov=reranking
          --cov=LLM
          --cov=Response
          --cov=utils
          --cov-report=term-missing

      - name: Check memory after tests
        if: always()
        run: docker stats --no-stream

      - name: Show logs on failure
        if: failure()
        run: docker compose logs postgres redis

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v